"use strict";
let isPHd = true;
let age = 21;
let userName = 'Sri Varu';
let salary = 1234567890n;
let notDefined = undefined;
let notPresent = null;
let penta = Symbol('star');
console.log(`Is Phd: ${isPHd}`);
console.log(`Age: ${age}`);
console.log(`Name: ${userName}`);
console.log(`Salary: ${salary}`);
console.log(`Not Defined: ${notDefined}`);
console.log(`Not Present: ${notPresent}`);
console.log(`Symbol: ${String(penta)}`);
